language: minimal

services:
  - docker
  
before_install:
- docker pull shamtam/merpmod

script:
- docker run --rm -v "$PWD":/data/MerpMod -w /data/MerpMod/MerpMod shamtam/merpmod:latest make TARGETROM=A2UI001L all
