language: minimal
if: tag IS present
services:
- docker
before_install:
- docker pull shamtam/merpmod
script:
- docker run --rm -v "$PWD":/data/MerpMod -w /data/MerpMod/MerpMod shamtam/merpmod:latest
  /bin/bash -c 'while read t; do make TARGETROM=$t all; done < build_targets'
deploy:
  provider: releases
  token:
    secure: fGgQs5JXv6yeSHvpRIZABRdp6EXk+EiRAMJLEEvAlg0kX8FuU1J9D4qLRlGGf9Vqo+tSs9h9CBXMIzRq7NRsxPYwuedqfusQUklSNcANiyZqTlrrLKs07+S5hKqxF7NFlzfiYxgiKL+PQX55N9Vm1kbF2Kwd6Ek3Z5An0r4n5zfbSQ0gsDYSVp0rnOaGRlXmhWABrTkvxpqol9N7KfoYBP6LM+mbbEMtUE9b8H2TvMM0GuiXggxbN3W7Vi9YA6RTeCks9cd1IPxqehHU2qMhDMPZGKyub/ictwCCYUBGwf12tqoA758YjYWjoZIgVQfSZhK3YZ3/t5mJ53B67so3P6AwstdHTw9MmJt/vYxhnFDS+IJbmsdoahiRg3oWH9bbo4qCP9YZZ5c0iTVisvim4/pqOOme6631c9eVCePftZR2TXcUA/0BcQlzGpiNEQzfXfA5y+vcMpsPQpqM0f4C6/SAHST7dwh+6utt+uWVQuSD6+EOX8KEMvifcR07yHVt+ZS9R8XUZqZ1TJUD+LbqGTkkoQ0cf4uuXd1LdbLzawJaNe3GKOVONQj3tqzkW4xwqcg0+2Nm+9vDRRWIJ49TVu/QaWfNFpCJmvDGNJC9A/56Ynv1g0AfODKNseclrdqw84NNWJv/mLrnDZIrClqjz2Nvi3t1qZ+MfMnH2KUH3+8=
  file: ./MerpMod/build/**/*.mot
  overwrite: true
  draft: true
  edge: true
  on:
    repo: Shamtam/MerpMod
    all_branches: true
    tags: true
