language: minimal
if: tag IS present
services:
- docker
before_install:
- docker pull shamtam/merpmod
script:
- docker run --rm -v "$PWD":/data/MerpMod -w /data/MerpMod/MerpMod shamtam/merpmod:latest
  /bin/bash -c 'while read t; do make TARGETROM=$t all; done < build_targets'
deploy:
  provider: releases
  token:
    secure: kvjE3TULoerV0wt38i8iRtTHYzjMg4zsMSXOfYnC6lQrjvxJvgKTe5t9/X+Vlu5vQqR9zQyHRtSU22GDVCzyFiCYj5uJi9xX/fU+VyUpTGlYfHdpJ2HiomXe+T7Nu9SixWt6DhU24P7N39hGQTph8d9MxLKG54XPVT1WR09e7r1vF8ggGHPiBE6aYhIhwlvV2QYZZEm8B4kypqLgN7LjluwreQJcc2NdmrzxtcpgSaJ7khpuznhsgcs440dTcrxhP6HqmOKfg02BSTlDV5IvJ0tjGd4Qc+l9wZmQNkuxaqtObDcSrhdaOfmXgyInDlhgYMUfVNnmm7YUX0g2ENhoP+vyvV92ewfqeagfR7squxkwDIaKjtmmOzlTxD8Og6AZbjFuTA5uMN6OtPJLvg3NBXDRxJIm5MBpMsGBhWvtsmikhyTizRLG8/tAogTqs+Yobfpdt0iQ9aHTfLoSs5YVEZ1Oy17dZgBK6EkxfMDyiemJ7CRQcrbgQ+WCozTwwLPtg+syQD8vNGfWEuI3SjScHV1Gcogd5nFbS5CA7nlqPCaPkvcXqNCMhqkhoUNNbbO0+u+UWTUOMQKOpMk05JIr0ejITrUzufgLl/I5GoajD5Y0Kj995oMLPp3/v+mElQXfiY06GsBq2BmrQ3VfZs8jPEwxiC6sMEWRVY4crYhY0u0=
  file: "./MerpMod/build/**/*.mot"
  overwrite: true
  edge: true
  on:
    repo: Shamtam/MerpMod
    branches: aijmod
    tags: true
